"""PDF report endpoints."""
from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, Response, status

from app.api.deps import AnalysisServiceDep, CurrentUser, ReportServiceDep
from app.api.v1.serializers import to_report
from app.core.rate_limit import report_rate_limit
from app.schemas.analysis import ErrorResponse, ReportSummary
from app.storage import get_storage

analysis_router = APIRouter(prefix="/analyses/{analysis_id}", tags=["Reports"])
report_router = APIRouter(prefix="/reports", tags=["Reports"])

_ERRORS = {
    401: {"model": ErrorResponse, "description": "Authentication required"},
    404: {"model": ErrorResponse, "description": "Analysis or report not found"},
    429: {"model": ErrorResponse, "description": "Report rate limit reached"},
}


@analysis_router.post(
    "/report",
    response_model=ReportSummary,
    status_code=status.HTTP_201_CREATED,
    responses=_ERRORS,
    summary="Generate a PDF report",
    description=(
        "Renders a multi-page PDF consultancy report from the stored analysis: cover "
        "page with the original photograph, executive summary, detected style and "
        "evidence, furniture and materials, colour palette, room-health scores, "
        "improvement recommendations, all three budget packages and the latest "
        "before/after visualization. If the AI narrative service is unavailable the "
        "report is still produced using a deterministic narrative."
    ),
    dependencies=[Depends(report_rate_limit)],
)
async def create_report(
    analysis_id: uuid.UUID,
    user: CurrentUser,
    analyses: AnalysisServiceDep,
    reports: ReportServiceDep,
) -> ReportSummary:
    analysis = await analyses.get_owned(user, analysis_id)
    report = await reports.generate(analysis, user)
    return to_report(report, analysis)


@report_router.get(
    "",
    response_model=list[ReportSummary],
    responses=_ERRORS,
    summary="List your reports",
    description="Returns every report generated by the authenticated user, newest first.",
)
async def list_reports(user: CurrentUser, reports: ReportServiceDep) -> list[ReportSummary]:
    rows = await reports.list_for_user(user)
    return [to_report(report, analysis) for report, analysis in rows]


@report_router.get(
    "/{report_id}",
    response_model=ReportSummary,
    responses=_ERRORS,
    summary="Get report metadata",
    description="Returns metadata for a single report owned by the authenticated user.",
)
async def get_report(
    report_id: uuid.UUID, user: CurrentUser, reports: ReportServiceDep
) -> ReportSummary:
    report = await reports.get_owned(user, report_id)
    return to_report(report)


@report_router.get(
    "/{report_id}/download",
    responses={**_ERRORS, 200: {"content": {"application/pdf": {}}}},
    summary="Download a report PDF",
    description=(
        "Streams the PDF as a file download. Ownership is verified on every request, "
        "so report URLs are not publicly accessible."
    ),
    response_class=Response,
)
async def download_report(
    report_id: uuid.UUID, user: CurrentUser, reports: ReportServiceDep
) -> Response:
    report = await reports.get_owned(user, report_id)
    data = get_storage().read(report.file_path)
    return Response(
        content=data,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{report.file_name}"',
            "Cache-Control": "private, no-store",
        },
    )
